/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Jobs": "工作",
    "This game is a work of satire and is not meant to offend or trivialize the serious issue of\n                homelessness.\n                It aims to raise awareness about the challenges faced by homeless individuals while using game mechanics\n                to illustrate systemic barriers and daily struggles. The content is fictional and may not represent all\n                experiences of homelessness.": "这个游戏是一部讽刺作品，并不是为了冒犯或轻视无家可归的严重问题。它旨在提高人们对无家可归者所面临挑战的认识，同时使用游戏机制来说明系统障碍和日常斗争。内容是虚构的，可能并不代表所有无家可归的经历。",
    "Buy": "购买",
    "Apply": "同意",
    "Beg for\n                    Money": "乞讨要钱",
    "Reset Data": "重置数据",
    "Begging": "乞讨",
    "F*ck This!": "骂骂咧咧!",
    "Enter Game": "进入游戏",
    "Leave": "离开",
    "Market": "市场",
    "Mastery": "精通",
    "Study": "学习",
    "Upgrades": "升级",
    "The Streets": "街道",
    "Visit\n                    Hospital": "访问医院",
    "Disclaimer": "免责声明",
    "Continue": "继续",
    "Play Music": "播放音乐",
    "Streets": "街道",
    "Run Away": "逃跑",
    "Waiter/Waitress": "服务生/女服务员",
    "Think Fast!": "快速思考！",
    "Accountant": "会计",
    "Associate's Degree": "副学士",
    "Associate's Degree Jobs": "副学士职位",
    "Attempt": "尝试",
    "Bachelor's Degree": "学士学位",
    "Bachelor's Degree Jobs": "学士学位工作",
    "Busk": "街头表演",
    "Busking": "街头表演",
    "Cashier": "收银员",
    "Chief Technology Officer": "首席技术官",
    "Consume Drugs": "使用药物",
    "Current Job": "目前的工作",
    "Data Scientist": "数据科学家",
    "Dental Assistant": "牙科助理",
    "Not started": "未开始",
    "Disclaimer": "免责声明",
    "Doctorate": "博士学位",
    "Doctorate Jobs": "博士学位工作",
    "Dumpster Dive": "垃圾站潜水",
    "Dumpster Diving": "垃圾站潜水",
    "Education": "教育",
    "Explore the Streets": "探索街道",
    "Explore the streets and find a new location.": "探索街道，找到一个新的位置。",
    "Fight Killer": "和杀手对战",
    "Game Over": "游戏结束",
    "GED": "GED",
    "GED Jobs": "GED职位",
    "Guitar": "吉他",
    "Heads": "人头",
    "Homeless Shelter": "收容所",
    "House": "房子",
    "Housing": "住房",
    "Initiate Killer": "初始杀手",
    "Junior Web Developer": "初级Web开发人员",
    "Lead groundbreaking research at a prestigious institution.": "在知名机构领导开创性的研究。",
    "Mansion": "大厦",
    "Marketing Manager": "营销经理",
    "Marketplace": "市场",
    "Master's Degree": "硕士学位",
    "Master's Degree Jobs": "硕士学位工作",
    "Meet the Dealer": "与经销商会面",
    "Meet the dealer and to gain access to drugs to use them to increase your energy.": "会见经销商和获得药物使用他们来增加你的能量。",
    "Nose Plugs": "鼻塞",
    "Paralegal Assistant": "律师助理",
    "Pass your Associate's Degree to qualify for a better job and to progress further in your education.": "通过你的副学士学位，有资格获得更好的工作，并在你的教育中取得进一步的进步。",
    "Pass your Bachelor's Degree to qualify for a better job and to progress further in your education.": "通过你的学士学位，有资格获得一份更好的工作，并在你的教育中进一步进步。",
    "Pass your Doctorate to qualify for the best jobs and to progress further in your education.": "通过你的博士学位，你就有资格获得最好的工作，并在你的教育中取得进一步的进步。",
    "Pass your GED to get your first job and to progress further in your education.": "通过GED考试，你就可以得到你的第一份工作，并在你的教育中进一步进步。",
    "Pass your Master's Degree to qualify for a better job and to progress further in your education.": "通过你的硕士学位，有资格获得一份更好的工作，并在你的教育中进一步进步。",
    "Private Studio": "私人工作室",
    "Project Director": "项目总监",
    "Reason:": "原因:",
    "Replace Me": "代替我",
    "Research Scientist": "研究科学家",
    "Rest (Skip Day)": "休息（跳过一天）",
    "Security Guard": "保安",
    "Senior Financial Analyst": "高级财务分析师",
    "Shared Apartment": "共享公寓",
    "Software Engineer": "软件工程师",
    "Speak to Homeless God": "与无家可归的上帝对话",
    "Tails": "背面",
    "Teach and conduct research at a university.": "在大学里教书并进行研究。",
    "The Homeless God will teach you how to truly survive on the streets, for a price.": "无家可归的上帝会教你如何真正在街头生存，这是有代价的。",
    "Time for Work!": "工作时间到了！",
    "University Professor": "大学教授",
    "Unlock your Associate's Degree to unlock this education": "解锁你的副学士学位来解锁这种教育",
    "Unlock your Bachelor's Degree to unlock this education": "解锁你的学士学位来解锁这种教育",
    "Unlock your GED to unlock this education": "解锁你的GED，解锁这个教育",
    "Unlock your Master's Degree to unlock this education": "解锁你的硕士学位来解锁这种教育",
    "Unlock your previous education to unlock this education": "解锁你以前的教育来解锁这个教育",
    "Unlocks the ability to dumpster dive and sell items for money.": "解锁垃圾箱潜水和出售物品赚钱的能力。",
    "Unlocks the ability to play music and busk for money.": "解锁播放音乐和卖艺赚钱的能力。",
    "Work as a cashier at a local store.": "在当地一家商店当收银员。",
    "Work as a CTO at a major tech company.": "在一家大型科技公司担任首席技术官。",
    "Work as a data scientist analyzing big data.": "作为数据科学家分析大数据。",
    "Work as a dental assistant in a dental clinic.": "在牙科诊所当牙医助理。",
    "Work as a junior web developer at a small company.": "在一家小公司做初级网页开发员。",
    "Work as a marketing manager for a medium-sized company.": "在一家中型公司做市场经理。",
    "Work as a paralegal assistant at a law firm.": "在一家律师事务所做律师助理。",
    "Work as a project director managing large-scale projects.": "作为项目总监管理大型项目。",
    "Work as a security guard at a local building.": "在当地的一栋大楼里当保安。",
    "Work as a senior financial analyst at an investment firm.": "在一家投资公司担任高级金融分析师。",
    "Work as a server at a restaurant.": "在餐馆当服务员。",
    "Work as a software engineer at a tech company.": "在一家科技公司做软件工程师。",
    "Work as an accountant at a corporate firm.": "在一家公司做会计。",
    "You have reached the end of your life.": "你已经走到了生命的尽头。",
    "Insane": "疯狂",
    "Who the F*ck are you?": "你是谁？",
    "You ran away from the killer!": "你从杀手手里逃出来了！",
    "Hard": "困难",
    "Mother F*cker!": "哎呀！",
    "You were killed by the killer.": "你被杀手杀死了。",
    "You Win!": "你赢了！",
    "You Lose!": "你输了！",
    "Medium": "中等",
    "Holy Sh*t!": "糟糕！",
    "You fought the killer and won!": "你战胜了杀手，取得了胜利！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Daily Income: $": "日常收入: $",
    "Energy Cost: ": "能量成本: ",
    "Sell (": "出售 (",
    "Success Rate: ": "成功率: ",
    "Old Clothes": "旧衣服",
    "Lifespan: ": "寿命: ",
    "Plastic Bottle": "塑料瓶",
    "Glass Bottle": "玻璃瓶",
    "Days Survived: ": "生存天数: ",
    "Codeine": "咖啡因",
    "Whiskey": "威士忌",
    "Used Electronics": "废旧电子产品",
    "Age: ": "年龄: ",
    "Bad Squares Left: ": "剩余坏格数：",
    "Difficulty: ": "难度: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/day": "/天",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\$([\d\.]+) \+$/,
    /^\$([\d\.]+)\)$/,
    /^\$([\d\.,]+)([\d\.]+)\)$/,
    /^([\d\.,]+)([\d\.]+)\)$/,
    /^\+ ([\d\.,]+)([\d\.]+)$/,
    /^\+ ([\d\.,]+)([\d\.]+)\$$/,
    /^\+ ([\d\.]+)\$$/,
    /^\+ ([\d\.]+)$/,
    /^\$([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+)\/each \+ (.+) mastery bonus$/, '$1\/每个 + $2 精通加成'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);